### ISSUE TITLE
Missing G5

### ISSUE THREAD

**Issue by cjhaviland** [celesteh/FisherPriceRecords#1]
Hey! I just started 3D printing and just had to try making these records for my kids Fisher Price. Something I did notice is that mine has 22 pins and you only had 21 notes listed. I went through with a tuner and found the missing note which was a G5.

**Comment by celesteh** [comment]
This is a good catch, thank you.

My 3d printer is disassembled, so I can't properly test this, but I think the problem would be fixed if line 18 of FischerPriceRecords.sc were changed from `allowedNotes = ["D#4", "G#4", "A#4", "C5", "D#5", "F5", "G#5", "A#5", "C6", "C#6", "D#6", "F6", "G6", "G#6", "A#6"].collect({|note|`

to `allowedNotes = ["D#4", "G#4", "A#4", "C5", "D#5", "F5", "G5" "G#5", "A#5", "C6", "C#6", "D#6", "F6", "G6", "G#6", "A#6"].collect({|note|`

If you can test this and it works, please do a pull request and I'll merge the code.

**Comment by cjhaviland** [comment]
Ok, I just submitted the PR. Another thing I noticed and I can start a new issue if you'd like, is the record render and print was 119mm whereas the OG records are 121mm. The holes line up perfectly though.

**Comment by celesteh** [comment]
Does the difference in diameter effect the playing at all?

**Comment by cjhaviland** [comment]
I don’t think so? My first attempt just didn’t print that well but that is most likely my printer settings. I didn’t get very defined pins. 
![Uploading D8BCF9B3-064D-4F71-8C9D-E5D2953358D8.jpeg…]()

**Comment by celesteh** [comment]
If the diameter turns out to be an problem, please open a new issue.
Thanks again for your work on this.
